### ISSUE TITLE
给个具体的使用例子吧

### ISSUE THREAD

**Issue by phonehold** [zscorpio/weChat#2]
给个具体的使用例子吧

**Comment by zscorpio** [comment]
不是有例子啊..

2013/4/17 phonehold notifications@github.com

**Comment by phonehold** [comment]
没调试通过。。 用example.php 输出是null

**Comment by zscorpio** [comment]
看不懂原理瞎调试....

2013/4/17 phonehold notifications@github.com

**Comment by ghost** [comment]
变了，这个用不了

**Comment by zscorpio** [comment]
早就知道变了...不都说了不更新了,商业了

2013/4/17 maomao2011 notifications@github.com

**Comment by phonehold** [comment]
好吧。谢谢
