### ISSUE TITLE
想问一下有没有可能在公众平台上发个链接调用打开已安装的app的？

### ISSUE THREAD

**Issue by LiJiefei** [zscorpio/weChat#3]
想问一下有没有可能在公众平台上发个链接调用打开已安装的app的？ 多谢～～～

**Comment by zscorpio** [comment]
没有试过  

## 

蝎紫
已使用 Sparrow (http://www.sparrowmailapp.com/?sig)

在 2013年7月6日星期六，下午4:33，Jiefei Li 写道：
